# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'U:\ocrt-nn-reconstruction\forms/ocrtProcessingDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_processingDialog(object):
    def setupUi(self, processingDialog):
        processingDialog.setObjectName("processingDialog")
        processingDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        processingDialog.resize(256, 306)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(processingDialog.sizePolicy().hasHeightForWidth())
        processingDialog.setSizePolicy(sizePolicy)
        processingDialog.setMinimumSize(QtCore.QSize(256, 306))
        processingDialog.setMaximumSize(QtCore.QSize(256, 306))
        self.loadingSpinner = QtWidgets.QGraphicsView(processingDialog)
        self.loadingSpinner.setGeometry(QtCore.QRect(0, 0, 256, 256))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadingSpinner.sizePolicy().hasHeightForWidth())
        self.loadingSpinner.setSizePolicy(sizePolicy)
        self.loadingSpinner.setMinimumSize(QtCore.QSize(256, 256))
        self.loadingSpinner.setMaximumSize(QtCore.QSize(256, 256))
        self.loadingSpinner.setAcceptDrops(False)
        self.loadingSpinner.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.loadingSpinner.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.loadingSpinner.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.loadingSpinner.setObjectName("loadingSpinner")
        self.statusLabel = QtWidgets.QLabel(processingDialog)
        self.statusLabel.setGeometry(QtCore.QRect(0, 256, 256, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.statusLabel.setFont(font)
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")

        self.retranslateUi(processingDialog)
        QtCore.QMetaObject.connectSlotsByName(processingDialog)

    def retranslateUi(self, processingDialog):
        _translate = QtCore.QCoreApplication.translate
        processingDialog.setWindowTitle(_translate("processingDialog", "Processing Ы"))
        self.statusLabel.setText(_translate("processingDialog", "Processing"))
